# Docs pour l'action de déploiement d'Azure Web Apps : https://github.com/Azure/webapps-deploy
# Plus d'Actions GitHub pour Azure : https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - parcinformatiquefodservice

on:
  push:
    branches:
      - racem
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

      - name: Upload Surefire reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: '${{ github.workspace }}/target/surefire-reports'

  deploy:
    runs-on: windows-latest
    needs: build
    if: success()
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Ceci est nécessaire pour demander le JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4C35AF22B739411B944697CA47D1B4AE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C044F8FC705C4C7DB6DA94FBA30B0CD0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CAFB13AD0F7342388B6550CDF5CEA77B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'parcinformatiquefodservice'
          slot-name: 'Production'
          package: '*.jar'
